version: '3.8'

services:
  product-service:
    build: ./services/product-service
    ports:
      - "3001:3001"
    restart: unless-stopped

  user-service:
    build: ./services/user-service
    ports:
      - "3002:3002"
    restart: unless-stopped

  cart-service:
    build: ./services/cart-service
    ports:
      - "3003:3003"
    restart: unless-stopped

  payment-service:
    build: ./services/payment-service
    ports:
      - "3004:3004"
    restart: unless-stopped